SEED_CATEGORIES = [
    {"name": "Δημοφιλή", "slug": "popular", "image": "https://images.unsplash.com/photo-1552580715-4d9bc27f1e2f?w=650"},
    {"name": "Προσφορές", "slug": "offers", "image": "https://images.unsplash.com/photo-1552580715-4d9bc27f1e2f?w=650"},
    {"name": "Πίτσες", "slug": "pizzas", "image": "https://images.unsplash.com/photo-1576830673997-8c76ff5c941d?w=650"},
    {"name": "Panozzo Box", "slug": "panozzo", "image": "https://images.pexels.com/photos/31587831/pexels-photo-31587831.jpeg?w=650"},
    {"name": "Καλτσόνε", "slug": "kaltsone", "image": "https://images.unsplash.com/photo-1655070249064-2556803629b6?w=650"},
    {"name": "Ζυμαρικά", "slug": "pasta", "image": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=650"},
    {"name": "Σαλάτες", "slug": "salads", "image": "https://images.unsplash.com/photo-1623073119837-076224785565?w=650"},
    {"name": "Ορεκτικά & Πιάτα", "slug": "appetizers", "image": "https://images.unsplash.com/photo-1681102328199-03d6355371f4?w=650"},
    {"name": "Γλυκά", "slug": "sweets", "image": "https://images.unsplash.com/photo-1626263468007-a9e0cf83f1ac?w=650"},
    {"name": "Ποτά", "slug": "drinks", "image": "https://images.pexels.com/photos/5532830/pexels-photo-5532830.jpeg?w=650"},
]

# sizes for pizzas — client can adjust from admin
PIZZA_SIZES = [{"label": "26cm (8 τμχ)", "price": 0}, {"label": "30cm (Οικογενειακή)", "price": 4.0}, {"label": "36cm (Γίγας)", "price": 8.0}]

PIZZA_EXTRAS = [
    {"name": "Έξτρα τυρί", "price": 1.0}, {"name": "Μπέικον", "price": 1.0},
    {"name": "Ζαμπόν", "price": 1.0}, {"name": "Πεπερόνι", "price": 1.0},
    {"name": "Μανιτάρια", "price": 0.8}, {"name": "Ελιές", "price": 0.5},
    {"name": "Πιπεριά", "price": 0.5}, {"name": "Cheddar sauce", "price": 1.0},
]

def _pizza(name, desc, img, price=7.50, popular=False):
    return {"category": "pizzas", "name": name, "desc": desc,
            "image": f"https://www.telecanto.gr/images/thumbs/{img}",
            "price": price, "sizes": PIZZA_SIZES, "extras": PIZZA_EXTRAS, "popular": popular}

SEED_PRODUCTS = [
    _pizza("Μαργαρίτα", "Ζυμώνουμε καθημερινά τη βάση, φρέσκια σάλτσα και gouda που λιώνει όπως πρέπει.", "margarita_1035714474.webp", 7.50, True),
    _pizza("Verde", "Φρέσκιες πράσινες πιπεριές, ζουμερά μανιτάρια, κρεμμύδι, χειροποίητη σως ντομάτας & gouda.", "verde_2981742819.webp"),
    _pizza("Μποργκέζε", "Καπνιστό τραγανό μπέικον, φρέσκα μανιτάρια & πράσινη πιπεριά.", "mporgkeze_621784719.webp"),
    _pizza("Ρομάνα", "Ζαμπόν που σου μιλάει ιταλικά, φρέσκα μανιτάρια & πιπεριά.", "romana_1259659420.webp"),
    _pizza("Τροπικάνα", "Γλυκός ανανάς, αλμυρό ζαμπόν και τυρί που λιώνει.", "tropikana_1858265046.webp"),
    _pizza("4 Εποχές", "Ζαμπόν, μπέικον, λουκάνικο, φρέσκα μανιτάρια.", "4-epoxes_6100200508.webp", 7.50, True),
    _pizza("Diavola", "Πιπερόνι, ελιές και καυτερό dressing στην κορυφή.", "diavola_1484523537.webp"),
    _pizza("Canto", "Η σπέσιαλ! Ζαμπόν, μπέικον, λουκάνικο πιπερόνε, μανιτάρια, πιπεριές.", "canto_1952587323.webp", 7.50, True),
    _pizza("4 Τυριά", "Απολαυστικό μίγμα λιωμένων τυριών - και το μοναδικό Ροκφόρ.", "4-tyria_1839521956.webp"),
    _pizza("Καρμπονάρα", "Λευκή σάλτσα καρμπονάρα, gouda, ζαμπόν, μπέικον & μανιτάρι.", "karmponara_1299244781.webp"),
    _pizza("Barbeque", "Ζουμερή σως BBQ, gouda, καπνιστό μπέικον & μανιτάρια.", "pizza-barbeque_6124300514.webp"),
    _pizza("Πιπερόνε", "Αυθεντική ιταλική με φρέσκια ζύμη, gouda & πιπερόνε.", "piperone_3236995670.webp"),
    _pizza("Αλλαντικών", "Ζαμπόν, μπέικον, λουκάνικο πιπερόνε & λιωμένο τυρί.", "pizza-allantikwn_2885825556.webp"),
    _pizza("Cheddar", "Σως ντομάτας, gouda, μπέικον & Cheddar sausage.", "pitsa-cheddar-26-cm_8122804422.webp", 8.50),
    _pizza("Κιμά", "Gouda, μίγμα μοσχαρίσιου & χοιρινού κιμά, πράσινη πιπεριά.", "kima_6207699849.webp", 8.00),
    _pizza("Τόνος", "Εκλεκτός τόνος, πράσινη πιπεριά, ελιές & gouda.", "tonos_9470221952.webp", 8.00),
    _pizza("Μακεδονία", "Gouda, λευκό τυρί, ντομάτα, κρεμμύδι, ελιές, πιπεριά & ρίγανη.", "makedonia_4097603147.webp", 8.00),
    _pizza("Λαχανικών", "Φρέσκα μανιτάρια, τραγανή πράσινη πιπεριά, gouda.", "laxanikwn_8272340816.webp"),
    _pizza("Σοκολατοπίτσα", "Μισή Bueno & μισή Nutella με Oreo.", "sokolatopitsa_7454333778.webp", 8.50),

    {"category": "panozzo", "name": "Panozzo Αλλαντικών",
     "desc": "Φρεσκοψημένο χειροποίτο ψωμάκι με μαγιονέζα, μαρούλι, ζαμπόν, πεπερόνι, gouda & ντομάτα. Με πατάτες τηγανητές.",
     "image": "https://www.telecanto.gr/images/thumbs/panozzo-allantikwn_7829807324.webp",
     "price": 8.50, "sizes": [], "extras": [], "popular": True},
    {"category": "panozzo", "name": "Panozzo Κοτομπουκιές",
     "desc": "Μεγάλο ψωμάκι με μαγιονέζα, μαρούλι, κοτομπουκιές, gouda & ντομάτα. Με πατάτες.",
     "image": "https://www.telecanto.gr/images/thumbs/panozzo-kotompoykies_4713166560.webp",
     "price": 8.50, "sizes": [], "extras": []},
    {"category": "panozzo", "name": "Panozzo Μπιφτέκι",
     "desc": "Ψωμάκι με μαγιονέζα, μαρούλι, μπιφτέκι, gouda & ντομάτα. Με πατάτες.",
     "image": "https://www.telecanto.gr/images/thumbs/panozzo-mpifteki_6712863690.webp",
     "price": 8.50, "sizes": [], "extras": []},
    {"category": "panozzo", "name": "Panozzo Hot Dog",
     "desc": "Ψωμάκι με μαγιονέζα, μαρούλι, λουκάνικο hot dog, gouda & ντομάτα.",
     "image": "https://www.telecanto.gr/images/thumbs/panozzo-hot-dog_931213757.webp",
     "price": 8.50, "sizes": [], "extras": []},

    {"category": "kaltsone", "name": "Καλτσόνε Μαργαρίτα", "desc": "Σάλτσα ντομάτας & τυρί.",
     "image": "https://www.telecanto.gr/images/thumbs/kaltsone-margarita_9050632117.webp",
     "price": 8.50, "sizes": [], "extras": []},
    {"category": "kaltsone", "name": "Καλτσόνε Ρομάνα", "desc": "Σάλτσα ντομάτας, τυρί, ζαμπόν, πιπεριά & μανιτάρια.",
     "image": "https://www.telecanto.gr/images/thumbs/kaltsone-romana_8200872507.webp",
     "price": 8.50, "sizes": [], "extras": []},
    {"category": "kaltsone", "name": "Καλτσόνε 4 Εποχές", "desc": "Ντομάτα, τυρί, ζαμπόν, μπέικον, σαλάμι & μανιτάρια.",
     "image": "https://www.telecanto.gr/images/thumbs/kaltsone-4-epoxes_839426065.webp",
     "price": 8.50, "sizes": [], "extras": []},
    {"category": "kaltsone", "name": "Καλτσόνε Diavola", "desc": "Πεπερόνι, ελιές & καυτερή.",
     "image": "https://www.telecanto.gr/images/thumbs/kaltsone-diavola_8238605142.webp",
     "price": 8.50, "sizes": [], "extras": []},
    {"category": "kaltsone", "name": "Καλτσόνε Τόνος", "desc": "Τόνος, ελιές & πιπεριά.",
     "image": "https://www.telecanto.gr/images/thumbs/kaltsone-tonos_5641293741.webp",
     "price": 8.50, "sizes": [], "extras": []},
    {"category": "kaltsone", "name": "Καλτσόνε Αυγό", "desc": "Ντομάτα, gouda, αυγό-ομελέτα, μπέικον & πιπεριά.",
     "image": "https://www.telecanto.gr/images/thumbs/kaltsone-aygo_8041459589.webp",
     "price": 5.80, "sizes": [], "extras": []},

    {"category": "pasta", "name": "Νάπολι", "desc": "Σάλτσα ντομάτας, σκόρδο & κεφαλοτύρι.",
     "image": "https://www.telecanto.gr/images/thumbs/napoli_2639714960.webp", "price": 5.50, "sizes": [], "extras": []},
    {"category": "pasta", "name": "Μπολονέζ", "desc": "Ντομάτα, κιμά, κρεμμύδι & κεφαλοτύρι.",
     "image": "https://www.telecanto.gr/images/thumbs/mpolonez_3183745703.webp", "price": 6.00, "sizes": [], "extras": [], "popular": True},
    {"category": "pasta", "name": "Καρμπονάρα", "desc": "Κρέμα γάλακτος, ζαμπόν, μπέικον, αυγό, μαϊντανός & κεφαλοτύρι.",
     "image": "https://www.telecanto.gr/images/thumbs/karmponara_892241806.webp", "price": 6.00, "sizes": [], "extras": []},
    {"category": "pasta", "name": "4 Τυριά", "desc": "Κρέμα γάλακτος, gouda, edam, emmental, ροκφόρ.",
     "image": "https://www.telecanto.gr/images/thumbs/4-tyria_4517881864.webp", "price": 6.00, "sizes": [], "extras": []},
    {"category": "pasta", "name": "Αραμπιάτα", "desc": "Κρέμα γάλακτος, πικάντικη σάλτσα, ντομάτα, σκόρδο.",
     "image": "https://www.telecanto.gr/images/thumbs/arampiata_6644932113.webp", "price": 6.00, "sizes": [], "extras": []},
    {"category": "pasta", "name": "Meatball Lovers", "desc": "Κεφτεδάκια με σάλτσα Ναπολιτάνα & παρμεζάνα.",
     "image": "https://www.telecanto.gr/images/thumbs/meatball-lovers_9601327653.webp", "price": 8.00, "sizes": [], "extras": []},
    {"category": "pasta", "name": "Tortellini 4 Τυριά", "desc": "Κρέμα γάλακτος, gouda, edam, emmental, ροκφόρ.",
     "image": "https://www.telecanto.gr/images/thumbs/tortelinia-4-tyria_5648077257.webp", "price": 7.50, "sizes": [], "extras": []},

    {"category": "salads", "name": "Σαλάτα Σεφ 1100ml", "desc": "Μαρούλι, λάχανο, αγγουροντομάτα, ζαμπόν, emmental, σως σεφ & αυγό.",
     "image": "https://www.telecanto.gr/images/thumbs/sef-1100ml_6418501503.webp", "price": 7.00, "sizes": [], "extras": []},
    {"category": "salads", "name": "Σαλάτα Κοτόπουλο 1100ml", "desc": "Με φρέσκα κομμάτια κοτόπουλο.",
     "image": "https://www.telecanto.gr/images/thumbs/kotopoylo-1100ml_6844552124.webp", "price": 7.00, "sizes": [], "extras": []},
    {"category": "salads", "name": "Σαλάτα 4 Εποχές 1100ml", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/4-epoxes-1100ml_3788838144.webp", "price": 7.00, "sizes": [], "extras": []},
    {"category": "salads", "name": "Vegetarian 1100ml", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/vegetarian-1100ml_6274024162.webp", "price": 7.00, "sizes": [], "extras": []},
    {"category": "salads", "name": "Αγγουροντομάτα", "desc": "Αγγουροντομάτα, κρεμμύδι, ελιές & ρίγανη.",
     "image": "https://www.telecanto.gr/images/thumbs/aggoyrontomata_4211498492.webp", "price": 7.50, "sizes": [], "extras": []},

    {"category": "appetizers", "name": "Πατάτες τηγανητές", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/patates-thganhtes_4835495548.webp", "price": 2.50, "sizes": [], "extras": []},
    {"category": "appetizers", "name": "Πατάτες με cheddar & μπέικον", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/patates-me-cheddar-mpeikon_6949592274.webp", "price": 4.00, "sizes": [], "extras": [], "popular": True},
    {"category": "appetizers", "name": "10 Κοτομπουκιές", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/10-kotompoykies_4528517430.webp", "price": 5.00, "sizes": [], "extras": []},
    {"category": "appetizers", "name": "Loaded Fries Crispy Chicken Bowl", "desc": "Τηγανιτές με cheddar, κοτομπουκιές, μαρούλι, ντομάτα, μαγιονέζα & κέτσαπ.",
     "image": "https://www.telecanto.gr/images/thumbs/loaded-fries-crispy-chicken-burger-bowlatomikh-merida_5080471886.webp", "price": 5.50, "sizes": [], "extras": [], "popular": True},
    {"category": "appetizers", "name": "Σκορδόψωμο με μοτσαρέλα", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/skordopswmo-me-motsarela_2893877561.webp", "price": 7.00, "sizes": [], "extras": []},
    {"category": "appetizers", "name": "Μπιφτέκι μερίδα", "desc": "2 τεμ., με πατάτες, τυρί, ντομάτα, μαρούλι, ketchup & μουστάρδα.",
     "image": "https://www.telecanto.gr/images/thumbs/mpifteki-merida_7435717651.webp", "price": 7.50, "sizes": [], "extras": []},
    {"category": "appetizers", "name": "Stromboli Pepperoni & Gouda", "desc": "Γεμιστό, garlic butter, παρμεζάνα, με πατάτες & ketchup.",
     "image": "https://www.telecanto.gr/images/thumbs/stromboli-pepperoni-gouda_6898287566.webp", "price": 10.00, "sizes": [], "extras": []},

    {"category": "sweets", "name": "Γλυκό Μεγάλο Σάντουιτς", "desc": "Πραλίνες Bueno, Nutella & τριμμένο Oreo.",
     "image": "https://www.telecanto.gr/images/thumbs/glyko-megalo-santoyits_5650917555.webp", "price": 8.50, "sizes": [], "extras": []},

    {"category": "drinks", "name": "Νερό 500ml", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/nero-500ml_2739245207.webp", "price": 0.50, "sizes": [], "extras": []},
    {"category": "drinks", "name": "Coca-Cola 330ml", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/coca-cola-330ml_6029281176.webp", "price": 1.50, "sizes": [], "extras": []},
    {"category": "drinks", "name": "Coca-Cola Zero 330ml", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/coca-cola-zero-330ml_2628865666.webp", "price": 1.50, "sizes": [], "extras": []},
    {"category": "drinks", "name": "Sprite 330ml", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/sprite-330ml_5416938879.webp", "price": 1.50, "sizes": [], "extras": []},
    {"category": "drinks", "name": "Coca-Cola 1.5lt", "desc": "",
     "image": "https://www.telecanto.gr/images/thumbs/coca-cola-1.5lt_8295903860.webp", "price": 3.00, "sizes": [], "extras": []},
    {"category": "drinks", "name": "Fix 330ml", "desc": "Μπύρα.",
     "image": "https://www.telecanto.gr/images/thumbs/fix-330ml_1464471649.webp", "price": 2.00, "sizes": [], "extras": []},
]
